### ISSUE TITLE
Found your app looking to add articles via rss to a db

### ISSUE THREAD

**Issue by DynaMc** [mtracy/News-Aggregation#1]
Hi, 

I found your script while searching for a script to add news articles to a database. How are you using this right now? 

Thanks

**Comment by mtracy** [comment]
Hi,

The script pulls info from specified RSS feeds, then matches each news
title to a news topic. The resulting info is stored into a postgres
database. Why do you ask?

Best,

-Mitchell

**Comment by DynaMc** [comment]
I wanted to use what you've got for my own needs. I had readrss.py adding to the db fine. Although that was only one URL (RSSl via command line. I see that runner.sh wanted the input feeds.json but it was not working correctly before I needed to quit for the night. Hemce, I thought I would ask about it. 

In my use case I was hoping to grab a summary of text as well. My goal is to feed these articles via title, summary text and URL to another website via API. like a news summary bot on a forum. 

Thanks,

**Comment by mtracy** [comment]
Oh sure! Actually I need to delete the json file. It proved to be too
annoying to read the json into a bash runner file. Take a look at
/input/feeds. That's a pipe delimited file that the runner actually reads
from. Also, the readrss file should be grabbing a summary of each news
article if it exists in the RSS. I will update that and the readme later
tonight and add a license.

**Comment by mtracy** [comment]
Hey I just updated a bunch of things. The readme should give pretty good direction on how to use it now. Let me know if something doesn't work now (I'm currently putting my free time into my repo called Topical which is very early on in dev). Additionally, about using this app at any sort of scale, I would email the guys here http://swoogle.umbc.edu/SimService/api.html unless you plan on removing the part where it computes the sematic similarity, since it uses an api that they provided. So you might want to just get in touch with them if you plan on using it a bunch since i don't see any usage information on their site.
